### ISSUE TITLE
How to use the Azure Resource Explorer with Government cloud?

### ISSUE THREAD

**Issue by ph5x5** [Azure/Service-Fabric-Troubleshooting-Guides#118]
We're using government cloud and need to update certificates for Service Fabric. I can't login with my account to the https://resources.azure.com/ like it's described [there](https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Security/Use%20Azure%20Resource%20Explorer%20to%20add%20the%20Secondary%20Certificate.md).
Which endpoint should I use to access Azure Resources Explorer from Gov account?
Or is there another way to update certificate for Service Fabric cluster?
Thanks in advance.

**Comment by jagilber** [comment]
@ph5x5 there may be restrictions for gov clouds access to resources.azure.com. 
there are multiple options for certs including powershell depending on what specifically you are adding / modifying:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-security-update-certs-azure

if options in link above do not resolve, i have used this generic resource script instead of resources.azure.com.
https://github.com/jagilber/powershellScripts/blob/master/azure-az-patch-resource.ps1

note this script has had limited testing and is provided as is.
test in non production environment first.
if you need assistance with your certificate swap, it may be best to open a support case with microsoft.
if you need assistance with this script feel free to ping me.

**to use:**

```powershell
(new-object net.webclient).DownloadFile("https://raw.githubusercontent.com/jagilber/powershellScripts/master/azure-az-patch-resource.ps1","$pwd\azure-az-patch-resource.ps1")
.\azure-az-patch-resource.ps1 -resourceGroupName {{ resource group name }} -resourceName {{ resource name }} [-patch]
```

**example enumeration (GET) steps 2 - 8 for nodetype:**

this will enumerate nodetype/vmss resource named 'nt0' from resource group 'sfjagilbercluster':

```powershell
.\azure-az-patch-resource.ps1 -resourceGroupName sfjagilbercluster -resourceName nt0
```

**make changes in template.json (steps 2 - 8)**

**example (PUT) steps 2 - 8 for nodetype:**

this will update nodetype/vmss resource named 'nt0' in resource group 'sfjagilbercluster':

```powershell
.\azure-az-patch-resource.ps1 -resourceGroupName sfjagilbercluster -resourceName nt0 -patch
```

**example enumeration (GET) steps 9 - 13 for cluster:**

this will enumerate service fabric cluster resource named 'sfjagilbercluster':

```powershell
.\azure-az-patch-resource.ps1 -resourceGroupName sfjagilbercluster -resourceName sfjagilbercluster
```

**make changes in template.json (steps 9 - 13)**

**example (PUT) steps 9 - 13 for cluster:**

this will update service fabric cluster resource named 'sfjagilbercluster':

```powershell
.\azure-az-patch-resource.ps1 -resourceGroupName sfjagilbercluster -resourceName sfjagilbercluster -patch
```

**example enumeration (GET) steps 14 - 18 for nodetype:**

this will enumerate nodetype/vmss resource named 'nt0' from resource group 'sfjagilbercluster':

```powershell
.\azure-az-patch-resource.ps1 -resourceGroupName sfjagilbercluster -resourceName nt0
```

**make changes in template.json (steps 14 -18)**

**example (PUT) steps 14 - 18 for nodetype:**

this will update nodetype/vmss resource named 'nt0' in resource group 'sfjagilbercluster':

```powershell
.\azure-az-patch-resource.ps1 -resourceGroupName sfjagilbercluster -resourceName nt0 -patch
```

**example enumeration (GET) steps 19 - 22 for cluster:**

this will enumerate service fabric cluster resource named 'sfjagilbercluster':

```powershell
.\azure-az-patch-resource.ps1 -resourceGroupName sfjagilbercluster -resourceName sfjagilbercluster
```

**make changes in template.json (steps 19 - 22)**

**example (PUT) steps 19 - 22 for cluster:**

this will update service fabric cluster resource named 'sfjagilbercluster':

```powershell
.\azure-az-patch-resource.ps1 -resourceGroupName sfjagilbercluster -resourceName sfjagilbercluster -patch
```
