### ISSUE TITLE
AAD Enabled Cluster Activity Logs

### ISSUE THREAD

**Issue by brianstringfellow** [Azure/Service-Fabric-Troubleshooting-Guides#76]
Where are the activity logs when accessing the cluster by AAD authentication?

For example, when publishing an application using 
`Connect-ServiceFabricCluster -ConnectionEndpoint $sfcConnectionEndpoint -AzureActiveDirectory -ServerCertThumbprint $certThumbprint`, I would expect the activity of publishing or deleting applications to be logged. I checked the connected storage account tables for logs and don't see any logs indicating which user took action. One particular table that I thought may contain information is empty ( `fabriclog<GUID>Client`).

**Comment by sedwardstx** [comment]
Hi Brian,

The activity itself is logged but any pii (personal identifiable information) such as the user name or IP address of person uploading would not be captured in any Service Fabric logs.  However if you are mainly interested in the AAD authentication event I would suggest correlating the SF events with AAD sign-in activity https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/concept-sign-ins.
 
Otherwise for general event details in SF we recommend using the EventStore service, which should be enabled by default, https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-eventstore

If you are interested in the logs or trace details you can find details for the add/delete application operations in the connected storage account usually named with the "sflog" prefix.  

The first and easiest would be fabriclog{someguid}ApplicationOps, look for EventType == ApplicationCreatedOperational or ApplicationDeletedOperational

The second place would be the actual SF traces which are located in the Blob Containers in a file named fabriclogs-{someguid}.  These are very verbose node level logs which are mainly used by support to troubleshoot issues in the cluster.  But if you want to look at the details in these files you can use Azure storage explorer to download, unzip, and convert the .dtr format to a .csv format using the following cmd.

   relog.exe {trace_file_name.dtr} -f csv -o {trace_file_name.csv}

**Comment by brianstringfellow** [comment]
I've been digging through the logs in both the `fabriclog{someguid}ApplicationOps` table and AAD 'Sign-ins'. I can see records in both sources related to deploying an application. In AAD, the records have a `Request ID` and `Correlation ID`. In the ApplicationOps table, I see the `ApplicationDeletedOperational` and `ApplicationCreatedOperational`. I can approximately correlate by timestamp but would like to see a record more concrete, such as matching `Request ID` or `Correlation ID` values. I'll have a look into the SF traces when I find more time.
